# Generated by Django 3.1.2 on 2020-10-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updateDate',
        ),
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(default='', max_length=50),
        ),
    ]
