# Generated by Django 3.1.2 on 2020-10-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201021_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='readcnt',
            field=models.IntegerField(default=0),
        ),
    ]
